#!/bin/sh

dotupdate() {
    echo "### Updating Fizzadar's .dotfiles..."
    echo

    # Check ~/.dotfiles directory exists
    if [ ! -d ~/.dotfiles ]; then
        echo "--> No ~/.dotfiles located, failing!"
        exit 1
    fi

    # Get current directory, jump to .dotfiles
    local old_dir=`pwd`
    cd ~/.dotfiles

    # Pull git updates
    git pull > /dev/null

    # Init/update submodules
    git submodule init > /dev/null
    git submodule update > /dev/null

    # Jump back to original permission
    cd "${old_dir}"

    # Loop through all dotfiles in ~/.dotfiles
    for file in ` \
        find ~/.dotfiles/.* \
        -type f -maxdepth 0 \
        | grep -v .DS_Store \
        | grep -v .gitmodules \
    `; do
        local filename=`basename ${file}`

        if [ -h "${HOME}/${filename}" ]; then
            echo "--> ${filename} already symlinked"
        else
            echo "--> Linking: ${file} -> ~/${filename}"
            ln -s $file $HOME/$filename
        fi
    done
    echo

    echo "--> Sourcing update scripts"
    source ~/.dotfiles/update_scripts/checks
    source ~/.dotfiles/update_scripts/osx

    echo "--> Sourcing ~/.bash_profile"
    source ~/.bash_profile

    echo "<-- Update complete!"
}
