#!/bin/sh

function fizzenv() {
    if [ ! -f fizzenv.sh ]; then
        cat > fizzenv.sh << EOL
function fizzenv_activate() {
    # Activate commands go here!
    return 0
}

function fizzenv_deactivate() {
    # Deactivate commands go here!
    return 0
}
EOL
        nano fizzenv.sh
    fi

    export FIZZENV=`pwd`
    source fizzenv.sh
    fizzenv_activate || true
    unset fizzenv_activate
}

function _fizzenv_prompt() {
    local ret=$?
    if [ -z "$FIZZENV" ]; then
        if [ -f fizzenv.sh ]; then
            echo "# fizzenv: activating! ${FIZZENV}"
            fizzenv
        fi
    # No longer in a subdirectory of our original fizzenv.sh file
    # See: https://unix.stackexchange.com/questions/6435
    elif [ "${PWD##$FIZZENV}" = $PWD ]; then
        echo "# fizzenv: deactivating! ${FIZZENV}"
        fizzenv_deactivate
        unset fizzenv_deactivate
        unset FIZZENV
    fi

    return $ret
}
if ! [[ "$PROMPT_COMMAND" =~ _fizzenv_prompt ]]; then
  PROMPT_COMMAND="_fizzenv_prompt;$PROMPT_COMMAND";
fi
