#!/bin/sh

# Setup path
PATH=/opt/bin:/opt/sbin:/usr/local/sbin:$PATH
export PATH=$(brew --prefix coreutils)/libexec/gnubin:$PATH

# Make Python use UTF-8 encoding for output to stdin, stdout, and stderr.
export PYTHONIOENCODING='UTF-8'

# Prefer US English and use UTF-8
export LANG='en_US.UTF-8'
export LC_ALL='en_US.UTF-8'

# Nano > vim!
export EDITOR=nano

# Make .vagrant directories machine-specific
export VAGRANT_DOTFILE_PATH=".vagrant-`hostname`"
