# Styles...
foreground: &foreground "#f8f8f2"
background: &background "#282a36"
current_line: &current_line "#282a36"
selection: &selection "#44475a"
comment: &comment "#6272a4"
cyan: &cyan "#8be9fd"
green: &green "#50fa7b"
orange: &orange "#ffb86c"
pink: &pink "#F2318D"
purple: &purple "#bd93f9"
red: &red "#ff5555"
yellow: &yellow "#f1fa8c"
tableBackground: &tableBackground "#082330"

# Skin...
k9s:
  # General K9s styles
  body:
    fgColor: *foreground
    bgColor: default
    logoColor: *pink
  # Command prompt styles
  prompt:
    fgColor: *foreground
    bgColor: *background
    suggestColor: *pink
  # ClusterInfoView styles.
  info:
    fgColor: *pink
    sectionColor: *foreground
  # Dialog styles.
  dialog:
    fgColor: *foreground
    bgColor: *background
    buttonFgColor: *foreground
    buttonBgColor: *pink
    buttonFocusFgColor: *yellow
    buttonFocusBgColor: *pink
    labelFgColor: *orange
    fieldFgColor: *foreground
  frame:
    # Borders styles.
    border:
      fgColor: *selection
      focusColor: *current_line
    menu:
      fgColor: *foreground
      keyColor: *pink
      # Used for favorite namespaces
      numKeyColor: *pink
    # CrumbView attributes for history navigation.
    crumbs:
      fgColor: *foreground
      bgColor: *current_line
      activeColor: *current_line
    # Resource status and update styles
    status:
      newColor: *cyan
      modifyColor: *pink
      addColor: *green
      errorColor: *red
      highlightcolor: *orange
      killColor: *comment
      completedColor: *comment
    # Border title styles.
    title:
      fgColor: *foreground
      bgColor: *current_line
      highlightColor: *orange
      counterColor: *pink
      filterColor: *pink
  views:
    # Charts skins...
    charts:
      bgColor: default
      defaultDialColors:
        - *pink
        - *red
      defaultChartColors:
        - *pink
        - *red
    # TableView attributes.
    table:
      fgColor: *foreground
      bgColor: *tableBackground
      cursorFgColor: black
      cursorBgColor: *current_line
      # Header row styles.
      header:
        fgColor: *foreground
        bgColor: *tableBackground
        sorterColor: *pink
    # Xray view attributes.
    xray:
      fgColor: *foreground
      bgColor: *background
      cursorColor: *current_line
      graphicColor: *pink
      showIcons: false
    # YAML info styles.
    yaml:
      keyColor: *pink
      colonColor: *pink
      valueColor: *foreground
    # Logs styles.
    logs:
      fgColor: *foreground
      bgColor: *background
      indicator:
        fgColor: *foreground
        bgColor: *pink
