#!/bin/sh

# Disable the warning when changing a file extension
defaults write com.apple.finder FXEnableExtensionChangeWarning -bool false

# Display full POSIX path as Finder window title
defaults write com.apple.finder _FXShowPosixPathInTitle -bool true

# Disable shadow around window screenshots
defaults write com.apple.screencapture disable-shadow -bool true
